import { Inter } from "next/font/google";
import "./globals.css";
import TransitionProvider from "@/components/transitionProvided";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Sajid Ahmed Chowdhury",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <TransitionProvider>{children}</TransitionProvider>
      </body>
    </html>
  );
}
